In [117]:
import pandas as pd 
import altair as alt
alt.data_transformers.enable("vegafusion")

DataTransformerRegistry.enable('vegafusion')

In [118]:
data = pd.read_csv('../data/simpsons_script_lines_cleaned.csv', dtype={'word_count': 'Int64','timestamp_in_ms': 'Int64'})

In [119]:
data

,id,season,number_in_season,episode_id,line_number_in_episode,timestamp_in_ms,character_id,raw_character_text,normalized_text,word_count
0,9549,2,19,32,209,848000,464.0,Miss Hoover,no actually it was a little of both sometimes ...,31
1,9550,2,19,32,210,856000,9.0,Lisa Simpson,wheres mr bergstrom,3
2,9551,2,19,32,211,856000,464.0,Miss Hoover,i dont know although id sure like to talk to h...,22
3,9552,2,19,32,212,864000,9.0,Lisa Simpson,that life is worth living,5
4,9553,2,19,32,213,864000,40.0,Edna Krabappel-Flanders,the polls will be open from now until the end ...,33
...,...,...,...,...,...,...,...,...,...,...
132016,9544,2,19,32,204,831000,464.0,Miss Hoover,im back,2
132017,9545,2,19,32,205,839000,464.0,Miss Hoover,you see class my lyme disease turned out to be,10
132018,9546,2,19,32,206,842000,464.0,Miss Hoover,psy cho so ma tic,5
132019,9547,2,19,32,207,844000,119.0,Ralph Wiggum,does that mean you were crazy,6
132020,9548,2,19,32,208,845000,4.0,JANEY,no that means she was faking it,7

In [120]:
images = {
    'Marge Simpson': 'https://img.icons8.com/doodle/48/marge-simpson.png',
    'Homer Simpson': 'https://img.icons8.com/doodle/48/homer-simpson.png',
    'Bart Simpson': 'https://img.icons8.com/doodle/48/bart-simpson.png',
    'Lisa Simpson': 'https://img.icons8.com/doodle/48/lisa-simpson.png',
    'C. Montgomery Burns': 'https://img.icons8.com/doodle/48/charles-montgomery-burns.png',
    'Moe Szyslak': 'https://img.icons8.com/doodle/48/bartender-mo.png',
    'Frank Grimes': 'https://static.simpsonswiki.com/images/a/a0/Tapped_Out_Frank_Grimes_Icon_-_Relaxed.png',
    'Coyote': 'https://static.simpsonswiki.com/images/7/73/Tapped_Out_Space_Coyote_Icon_-_Happy.png',
    'Milhouse Van Houten': 'https://img.icons8.com/doodle/48/milhouse-van-houten.png',
    'Krusty the Clown':'https://img.icons8.com/doodle/48/krusty-the-clown.png',
    'Ralph Wiggum': 'https://img.icons8.com/doodle/48/ralf.png',
    'Chief Wiggum':'https://img.icons8.com/doodle/48/clancy-wiggum.png',
    'Ned Flanders':'https://img.icons8.com/doodle/48/ned-flanders.png',
    'Barney Gumble': 'https://img.icons8.com/doodle/48/barney-gumble.png',
    'Grampa Simpson': 'https://img.icons8.com/doodle/48/abraham-simpson.png',
    'Apu Nahasapeemapetilon': 'https://static.simpsonswiki.com/images/0/08/Tapped_Out_Apu_Icon_-_Happy.png',
    'Nelson Muntz':'https://static.simpsonswiki.com/images/0/0c/Tapped_Out_Nelson_Icon_-_Brave.png',
    'Groundskeeper Willie':'https://static.simpsonswiki.com/images/4/40/Tapped_Out_Chainsaw_Willie_Icon_-_Happy.png',
    'Duffman':'https://static.simpsonswiki.com/images/1/18/Tapped_Out_Duffman_Icon.png',
    'Dr. Julius Hibbert':'https://static.simpsonswiki.com/images/d/d5/Tapped_Out_Dr._Hibbert_Icon.png',
    'Edna Krabappel-Flanders':'https://static.simpsonswiki.com/images/1/14/Tapped_Out_Mrs._Krabappel_Icon.png',
    'Sideshow Bob':'https://static.simpsonswiki.com/images/6/68/Tapped_Out_Sideshow_Bob_Icon_-_Serious.png',
    'Waylon Smithers':'https://static.simpsonswiki.com/images/3/3a/Tapped_Out_Smithers_Icon.png',
    'Lenny Leonard':'https://static.simpsonswiki.com/images/6/6f/Tapped_Out_Lenny_Icon.png',
    'Carl Carlson':'https://static.simpsonswiki.com/images/a/a4/Tapped_Out_Carl_Icon.png',
    'Kent Brockman':'https://static.simpsonswiki.com/images/3/35/Tapped_Out_Brockman_Sidebar.png',
    'Rev. Timothy Lovejoy':'https://static.simpsonswiki.com/images/4/40/Tapped_Out_Rev._Lovejoy_Sidebar.png',
    'Mayor Joe Quimby':'https://static.simpsonswiki.com/images/e/e3/Tapped_Out_Quimby_Icon.png',
    'Comic Book Guy':'https://static.simpsonswiki.com/images/a/a9/Tapped_Out_Comic_Book_Guy_Icon.png',
    'Gary Chalmers':'https://static.simpsonswiki.com/images/5/58/Tapped_Out_Chalmers_Icon.png',
    'Selma Bouvier':'https://static.simpsonswiki.com/images/8/8f/Tapped_Out_Selma_Icon.png',
    'Professor Jonathan Frink':'https://static.simpsonswiki.com/images/0/09/Tapped_Out_Professor_Frink_Icon_-_Deadpan.png',
    'Patty Bouvier':'https://static.simpsonswiki.com/images/3/31/Tapped_Out_Patty_Sidebar.png',
    'Martin Prince':'https://static.simpsonswiki.com/images/d/da/Tapped_Out_Martin_Icon.png',
    'Otto Mann':'https://static.simpsonswiki.com/images/4/48/Tapped_Out_Conductor_Otto_Sidebar.png',
    'Sideshow Mel':'https://static.simpsonswiki.com/images/6/6d/Tapped_Out_Sideshow_Mel_Icon.png',
    'Fat Tony':'https://static.simpsonswiki.com/images/1/1b/Tapped_Out_Fat_Tony_Icon.png',
    'Lou':'https://static.simpsonswiki.com/images/c/cf/Tapped_Out_Lou_Icon.png',
    'Jimbo Jones':'https://static.simpsonswiki.com/images/f/f3/Tapped_Out_Jimbo_Icon.png',
    'Kirk Van Houten':'https://static.simpsonswiki.com/images/6/61/Tapped_Out_Acorn_Kirk_Icon.png',
    'Agnes Skinner':'https://static.simpsonswiki.com/images/b/b1/Tapped_Out_Agnes_Sidebar.png',
    'Cletus Spuckler': 'https://static.simpsonswiki.com/images/a/a0/Tapped_Out_Cletus_Icon_-_Smiling.png'
}

# Q1 - What are the characters that issue more words, and how are the word numbers distributed?

In [121]:
data_q1 = data.groupby('raw_character_text')['word_count'].sum().reset_index()
data_q1

               raw_character_text  word_count
0            "For Dummies" Author           9
1     "Just Stamp the Ticket" Man          39
2                      "Mario" #2          10
3                   "Shorts" Bart          22
4                  "Shorts" Homer          47
...                           ...         ...
6269                         iPod           5
6270           newsstand Operator           7
6271                            t           1
6272                      teacher          51
6273                         Üter         105

[6274 rows x 2 columns]

In [122]:
top_characters = data_q1.sort_values(by='word_count', ascending=False)
top_characters
chart = alt.Chart(top_characters.head(20)).mark_bar().encode(
    x=alt.X('raw_character_text', sort='-y', title='Character'),
    y=alt.Y('word_count', title='Total Word Count'),
    tooltip=['raw_character_text', 'word_count']
).properties(
    title='Top 20 Characters by Total Word Count'
).configure_axisX(
    labelAngle=-45,
    labelFontSize=12
).configure_title(
    fontSize=16,
    anchor='start'
)
chart

alt.Chart(...)

In [123]:
#How are the word numbers distributed
chart = alt.Chart(data).mark_bar().encode(
    x=alt.X('word_count', bin=alt.Bin(maxbins=50), title='Word Count'),
    y=alt.Y('count()', title='Frequency'),
    tooltip=['count()']
).properties(
    title='Distribution of Word Counts'
).configure_title(
    fontSize=16,
    anchor='start'
)
chart

alt.Chart(...)

In [124]:
word_freq = (
    data.assign(word=data["normalized_text"].str.split())
        .explode("word")
        .groupby("word")
        .size()
        .reset_index(name="frequency")
)

word_freq

        word  frequency
0          0          6
1        007          1
2        07s          1
3          1         34
4         10         17
...      ...        ...
40833  ólive          1
40834    úna          2
40835   über          1
40836     Ĉu          1
40837     Ĝi          1

[40838 rows x 2 columns]

In [125]:
top_words = word_freq.sort_values(by='frequency', ascending=False).head(20)
chart = alt.Chart(top_words).mark_bar().encode(
    x=alt.X('word', sort='-y', title='Word'),
    y=alt.Y('frequency', title='Frequency'),
    tooltip=['word', 'frequency']
).properties(
    title='Top 20 Words by Frequency'
).configure_axisX(
    labelAngle=-45,
    labelFontSize=12
).configure_title(
    fontSize=16,
    anchor='start'
)
chart

alt.Chart(...)

In [126]:
chart = alt.Chart(word_freq[word_freq['frequency'] > 500]).mark_bar().encode(
    x=alt.X('frequency', bin=alt.Bin(maxbins=50), title='Frequency of Words'),
    y=alt.Y('count()', title='Frequency of Frequency of Words'),
    tooltip=['count()']
).properties(
    title='Distribution of Word frequencies'
).configure_title(
    fontSize=16,
    anchor='start'
)
chart

alt.Chart(...)

In [127]:
# for each character i want to count the number of unique words they have said
unique_words = data.groupby('raw_character_text')['normalized_text'].apply(lambda x: set(' '.join(x).split())).reset_index().rename(columns={'normalized_text': 'unique_words'})
unique_words['unique_word_count'] = unique_words['unique_words'].apply(len)
data_q1 = data_q1.merge(unique_words[['raw_character_text', 'unique_word_count']], on='raw_character_text', how='left')
data_q1.sort_values(by='word_count', ascending=False,inplace=True)
data_q1

        raw_character_text  word_count  unique_word_count
2680         Homer Simpson      273419              15891
3619         Marge Simpson      125349               9868
613           Bart Simpson      109983               9807
3323          Lisa Simpson       99857              10444
889    C. Montgomery Burns       36577               6288
...                    ...         ...                ...
4790                 Ricky           1                  1
138   6-YEAR OLD YOKEL BOY           1                  1
544        BURLY BARTENDER           1                  1
4794           Ring Bearer           1                  1
4484                Poonam           1                  1

[6274 rows x 3 columns]

In [128]:
characters = ['Homer Simpson','Bart Simpson','Marge Simpson','Lisa Simpson','Moe Szyslak','C. Montgomery Burns']
data_q1_main = data_q1[data_q1['raw_character_text'].isin(characters)]
data_q1_main
data_q1_main['image'] = data_q1_main['raw_character_text'].map(images)
data_q1_main

/var/folders/95/s4thp5290fd41pw2cj8713k80000gn/T/ipykernel_59502/2051398214.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_q1_main['image'] = data_q1_main['raw_character_text'].map(images)

,raw_character_text,word_count,unique_word_count,image
2680,Homer Simpson,273419,15891,https://img.icons8.com/doodle/48/homer-simpson...
3619,Marge Simpson,125349,9868,https://img.icons8.com/doodle/48/marge-simpson...
613,Bart Simpson,109983,9807,https://img.icons8.com/doodle/48/bart-simpson.png
3323,Lisa Simpson,99857,10444,https://img.icons8.com/doodle/48/lisa-simpson.png
889,C. Montgomery Burns,36577,6288,https://img.icons8.com/doodle/48/charles-montg...
3792,Moe Szyslak,33171,4881,https://img.icons8.com/doodle/48/bartender-mo.png

* https://iconos8.es/icons/set/simpson

* https://altair-viz.github.io/user_guide/marks/image.html
* https://github.com/vega/altair/issues/1949

In [129]:
plot = alt.Chart(data_q1.head(5)).mark_text().encode(
    x = alt.X('word_count', title='Total Word Count'),
    y = alt.Y('unique_word_count', title='Unique Word Count'),
    text = 'raw_character_text',
    tooltip = ['raw_character_text', 'word_count', 'unique_word_count']
)
plot

alt.Chart(...)

In [ ]:
alt.Chart(data_q1_main).mark_image(width=30, height=30).encode(
    x = alt.X('word_count', title='Total Word Count'),
    y = alt.Y('unique_word_count', title='Unique Word Count'),
    url = 'image',
    tooltip = ['raw_character_text', 'word_count', 'unique_word_count']
).properties(
    title='Total Word Count vs Unique Word Count for Main Characters'
).configure_title(
    fontSize=16,
    anchor='start'
)

alt.Chart(...)

In [131]:
characters_wiht_image = images.keys()
data_q1_image = data_q1[data_q1['raw_character_text'].isin(characters_wiht_image)]
data_q1_image['image'] = data_q1_image['raw_character_text'].map(images)
data_q1_image

/var/folders/95/s4thp5290fd41pw2cj8713k80000gn/T/ipykernel_59502/2441827274.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_q1_image['image'] = data_q1_image['raw_character_text'].map(images)

,raw_character_text,word_count,unique_word_count,image
2680,Homer Simpson,273419,15891,https://img.icons8.com/doodle/48/homer-simpson...
3619,Marge Simpson,125349,9868,https://img.icons8.com/doodle/48/marge-simpson...
613,Bart Simpson,109983,9807,https://img.icons8.com/doodle/48/bart-simpson.png
3323,Lisa Simpson,99857,10444,https://img.icons8.com/doodle/48/lisa-simpson.png
889,C. Montgomery Burns,36577,6288,https://img.icons8.com/doodle/48/charles-montg...
3792,Moe Szyslak,33171,4881,https://img.icons8.com/doodle/48/bartender-mo.png
4026,Ned Flanders,23380,4210,https://img.icons8.com/doodle/48/ned-flanders.png
3188,Krusty the Clown,20945,4023,https://img.icons8.com/doodle/48/krusty-the-cl...
1120,Chief Wiggum,20130,3616,https://img.icons8.com/doodle/48/clancy-wiggum...
2419,Grampa Simpson,19650,3638,https://img.icons8.com/doodle/48/abraham-simps...
3117,Kent Brockman,16177,4263,https://static.simpsonswiki.com/images/3/35/Ta...
3744,Milhouse Van Houten,14627,2948,https://img.icons8.com/doodle/48/milhouse-van-...
412,Apu Nahasapeemapetilon,11657,2681,https://static.simpsonswiki.com/images/0/08/Ta...
3274,Lenny Leonard,9917,2359,https://static.simpsonswiki.com/images/6/6f/Ta...
6051,Waylon Smithers,9604,2207,https://static.simpsonswiki.com/images/3/3a/Ta...
4034,Nelson Muntz,8551,2085,https://static.simpsonswiki.com/images/0/0c/Ta...
1670,Dr. Julius Hibbert,7821,2074,https://static.simpsonswiki.com/images/d/d5/Ta...
1751,Edna Krabappel-Flanders,7354,1790,https://static.simpsonswiki.com/images/1/14/Ta...
1019,Carl Carlson,7221,1923,https://static.simpsonswiki.com/images/a/a4/Ta...
4765,Rev. Timothy Lovejoy,6905,1973,https://static.simpsonswiki.com/images/4/40/Ta...
5188,Sideshow Bob,6444,1917,https://static.simpsonswiki.com/images/6/68/Ta...
3667,Mayor Joe Quimby,6173,1969,https://static.simpsonswiki.com/images/e/e3/Ta...
1253,Comic Book Guy,5813,1954,https://static.simpsonswiki.com/images/a/a9/Ta...
2284,Gary Chalmers,5759,1661,https://static.simpsonswiki.com/images/5/58/Ta...
5092,Selma Bouvier,4973,1382,https://static.simpsonswiki.com/images/8/8f/Ta...
4561,Professor Jonathan Frink,4876,1621,https://static.simpsonswiki.com/images/0/09/Ta...
2453,Groundskeeper Willie,4837,1480,https://static.simpsonswiki.com/images/4/40/Ta...
601,Barney Gumble,4508,1249,https://img.icons8.com/doodle/48/barney-gumble...
4359,Patty Bouvier,3816,1227,https://static.simpsonswiki.com/images/3/31/Ta...
3643,Martin Prince,3770,1457,https://static.simpsonswiki.com/images/d/da/Ta...
4251,Otto Mann,3615,1178,https://static.simpsonswiki.com/images/4/48/Ta...
5192,Sideshow Mel,3366,1302,https://static.simpsonswiki.com/images/6/6d/Ta...
4681,Ralph Wiggum,3061,941,https://img.icons8.com/doodle/48/ralf.png
1970,Fat Tony,2980,1036,https://static.simpsonswiki.com/images/1/1b/Ta...
3366,Lou,2712,942,https://static.simpsonswiki.com/images/c/cf/Ta...
2968,Jimbo Jones,2674,1001,https://static.simpsonswiki.com/images/f/f3/Ta...
3159,Kirk Van Houten,2514,862,https://static.simpsonswiki.com/images/6/61/Ta...
266,Agnes Skinner,2478,852,https://static.simpsonswiki.com/images/b/b1/Ta...
1207,Cletus Spuckler,2362,983,https://static.simpsonswiki.com/images/a/a0/Ta...
1715,Duffman,970,461,https://static.simpsonswiki.com/images/1/18/Ta...
2165,Frank Grimes,792,351,https://static.simpsonswiki.com/images/a/a0/Ta...
1358,Coyote,128,83,https://static.simpsonswiki.com/images/7/73/Ta...

In [134]:
x_enc = alt.X(
    "raw_character_text:N",
    sort=data_q1_image["raw_character_text"].tolist(),
    axis=alt.Axis(domain=False, ticks=False, labels=False,title = None)  # amaga labels de text
)

bars = alt.Chart(data_q1_image).mark_bar().encode(
    x=x_enc,
    y=alt.Y("word_count:Q", title="Total Word Count"),
    tooltip=["raw_character_text:N", "word_count:Q"]
)

flags = (
    alt.Chart(data_q1_image)
    .transform_calculate(zero="0")
    .mark_image(width=25, height=25, yOffset=14, clip=False)
    .encode(
        x= x_enc,
        y=alt.Y("zero:Q"),
        url="image:N"
    )
)

(bars + flags).resolve_scale(x="shared").properties(
    title="Total Word Count for Main Characters",
    height=360,
    width=800
)

alt.LayerChart(...)

# Q2 How have the word numbers among the characters evolved throughout the available seasons?

opció 1 -> agrupat per tota una temporada

In [136]:
data_q2_1 = data.groupby(['season','raw_character_text'])['word_count'].sum().reset_index()
data_q2_1

       season      raw_character_text  word_count
0           1      1st Waiter Quartet           9
1           1      2nd Waiter Quartet          14
2           1      3rd Waiter Quartet           8
3           1  4TH QUARTET OF WAITERS          19
4           1        ALL AT THE TABLE           1
...       ...                     ...         ...
10472      26        YOUNG JEWISH MAN          28
10473      26           YOUNG MOLEMAN          34
10474      26            Young Grampa          33
10475      26            Young Krusty           7
10476      26               Young Man          70

[10477 rows x 3 columns]

In [137]:
characters = ['Homer Simpson','Bart Simpson','Marge Simpson','Lisa Simpson','Moe Szyslak']
data_q2_1_main = data_q2_1[data_q2_1['raw_character_text'].isin(characters)]
data_q2_1_main['image'] = data_q2_1_main['raw_character_text'].map(images)
data_q2_1_main

/var/folders/95/s4thp5290fd41pw2cj8713k80000gn/T/ipykernel_59502/2058149966.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_q2_1_main['image'] = data_q2_1_main['raw_character_text'].map(images)

,season,raw_character_text,word_count,image
17,1,Bart Simpson,4902,https://img.icons8.com/doodle/48/bart-simpson.png
85,1,Homer Simpson,8183,https://img.icons8.com/doodle/48/homer-simpson...
111,1,Lisa Simpson,1883,https://img.icons8.com/doodle/48/lisa-simpson.png
125,1,Marge Simpson,3676,https://img.icons8.com/doodle/48/marge-simpson...
135,1,Moe Szyslak,443,https://img.icons8.com/doodle/48/bartender-mo.png
...,...,...,...,...
10227,26,Bart Simpson,2064,https://img.icons8.com/doodle/48/bart-simpson.png
10302,26,Homer Simpson,7621,https://img.icons8.com/doodle/48/homer-simpson...
10338,26,Lisa Simpson,2057,https://img.icons8.com/doodle/48/lisa-simpson.png
10356,26,Marge Simpson,3337,https://img.icons8.com/doodle/48/marge-simpson...
10362,26,Moe Szyslak,1835,https://img.icons8.com/doodle/48/bartender-mo.png

potser posar la cara a l'ultim / primer punt

In [138]:
lines = alt.Chart(data_q2_1_main).mark_line(point=True).encode(
    x=alt.X('season:O', title='Season'),
    y=alt.Y('word_count:Q', title='Total Word Count'),
    color=alt.Color('raw_character_text:N', title='Character'),
    tooltip=['season', 'raw_character_text', 'word_count']    
)
lines.properties(
    title='Total Word Count per Season for Main Characters'
).configure_title(
    fontSize=16,
    anchor='start'
).configure_axis(labelAngle=0)

alt.Chart(...)

In [139]:
area = alt.Chart(data_q2_1_main).mark_area(point=True).encode(
    x=alt.X('season:O', title='Season'),
    y=alt.Y('word_count:Q', title='Total Word Count'),
    color=alt.Color('raw_character_text:N', title='Character'),
    tooltip=['season', 'raw_character_text', 'word_count']    
)
area.properties(
    title='Total Word Count per Season for Main Characters'
).configure_title(
    fontSize=16,
    anchor='start'
).configure_axis(labelAngle=0)

alt.Chart(...)

In [140]:
points_faces = alt.Chart(data_q2_1_main).mark_image(width=20, height=20).encode(
x=alt.X('season:O', title='Season'),
y=alt.Y('word_count:Q', title='Total Word Count'),
url='image:N',
tooltip=['season:O', 'raw_character_text:N', 'word_count:Q']
)

lines = alt.Chart(data_q2_1_main).mark_line(strokeWidth=2).encode(
x=alt.X('season:O', title='Season'),
y=alt.Y('word_count:Q', title='Total Word Count'),
color=alt.Color('raw_character_text:N', title='Character', legend=None),
detail='raw_character_text:N'
)

(lines + points_faces).properties(
title='Total Word Count per Season for Main Characters'
).configure_title(
fontSize=16,
anchor='start'
).configure_axisX(
labelAngle=0
)

alt.LayerChart(...)

opcio 2 agrupat per cada capitol

In [141]:
data_q2_2 = data.groupby(['season', 'episode_id', 'raw_character_text'])['word_count'].sum().reset_index()
data_q2_2

       season  episode_id    raw_character_text  word_count
0           1           1             Announcer         131
1           1           1         Barney Gumble         116
2           1           1          Bart Simpson         337
3           1           1               Bubbles          17
4           1           1   C. Montgomery Burns          46
...       ...         ...                   ...         ...
20158      26         568          Ned Flanders          82
20159      26         568  Rev. Timothy Lovejoy         109
20160      26         568      SECURITY THUG #1          25
20161      26         568      SECURITY THUG #2          33
20162      26         568          Sideshow Mel          22

[20163 rows x 4 columns]

In [142]:
data_q2_2_main = data_q2_2[data_q2_2['raw_character_text'].isin(characters)]
data_q2_2_main['image'] = data_q2_2_main['raw_character_text'].map(images)
data_q2_2_main = data_q2_2_main.merge(data[['episode_id','number_in_season']].drop_duplicates(),how='left', on='episode_id')
data_q2_2_main

/var/folders/95/s4thp5290fd41pw2cj8713k80000gn/T/ipykernel_59502/4292786065.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_q2_2_main['image'] = data_q2_2_main['raw_character_text'].map(images)

,season,episode_id,raw_character_text,word_count,image,number_in_season
0,1,1,Bart Simpson,337,https://img.icons8.com/doodle/48/bart-simpson.png,1
1,1,1,Homer Simpson,909,https://img.icons8.com/doodle/48/homer-simpson...,1
2,1,1,Lisa Simpson,223,https://img.icons8.com/doodle/48/lisa-simpson.png,1
3,1,1,Marge Simpson,371,https://img.icons8.com/doodle/48/marge-simpson...,1
4,1,1,Moe Szyslak,26,https://img.icons8.com/doodle/48/bartender-mo.png,1
...,...,...,...,...,...,...
2622,26,567,Moe Szyslak,590,https://img.icons8.com/doodle/48/bartender-mo.png,15
2623,26,568,Bart Simpson,66,https://img.icons8.com/doodle/48/bart-simpson.png,16
2624,26,568,Homer Simpson,309,https://img.icons8.com/doodle/48/homer-simpson...,16
2625,26,568,Lisa Simpson,94,https://img.icons8.com/doodle/48/lisa-simpson.png,16
2626,26,568,Marge Simpson,450,https://img.icons8.com/doodle/48/marge-simpson...,16

In [143]:
points = alt.Chart(data_q2_2_main).mark_point(filled = True, size=60).encode(
    x=alt.X('episode_id:O', title='Season'),
    y=alt.Y('word_count:Q', title='Total Word Count'),
    color=alt.Color('raw_character_text:N', title='Character'),
    tooltip=['season', 'number_in_season','raw_character_text', 'word_count']
)

lines = alt.Chart(data_q2_2_main).mark_line().encode(
    x=alt.X('episode_id:O', title='Season'),
    y=alt.Y('word_count:Q', title='Total Word Count'),
    color=alt.Color('raw_character_text:N', title='Character')
    
)

(points + lines).properties(
    title='Total Word Count per Season for Main Characters',
    width=2000,
).configure_title(
    fontSize=16,
    anchor='start'
).configure_axisX(
    labelAngle=0,
)

alt.LayerChart(...)

# Q3 I would like to compare the word distribution for a pair of concrete characters, for a selected season, and, in addition, for a selected episode.

Assumim una sola season

In [144]:
data_q3 = data.groupby(['season', 'number_in_season', 'raw_character_text'])['word_count'].sum().reset_index()
data_q3['image'] = data_q3['raw_character_text'].map(images)
characters = ['Bart Simpson', 'Lisa Simpson']
data_q3 = data_q3[data_q3['season'] == 1]
data_q3 = data_q3[data_q3['raw_character_text'].isin(characters)]
data_q3

,season,number_in_season,raw_character_text,word_count,image
2,1,1,Bart Simpson,337,https://img.icons8.com/doodle/48/bart-simpson.png
18,1,1,Lisa Simpson,223,https://img.icons8.com/doodle/48/lisa-simpson.png
37,1,2,Bart Simpson,631,https://img.icons8.com/doodle/48/bart-simpson.png
48,1,2,Lisa Simpson,71,https://img.icons8.com/doodle/48/lisa-simpson.png
58,1,3,Bart Simpson,209,https://img.icons8.com/doodle/48/bart-simpson.png
71,1,3,Lisa Simpson,54,https://img.icons8.com/doodle/48/lisa-simpson.png
94,1,4,Bart Simpson,189,https://img.icons8.com/doodle/48/bart-simpson.png
100,1,4,Lisa Simpson,151,https://img.icons8.com/doodle/48/lisa-simpson.png
126,1,5,Bart Simpson,796,https://img.icons8.com/doodle/48/bart-simpson.png
134,1,5,Lisa Simpson,225,https://img.icons8.com/doodle/48/lisa-simpson.png
144,1,6,Bart Simpson,400,https://img.icons8.com/doodle/48/bart-simpson.png
154,1,6,Lisa Simpson,340,https://img.icons8.com/doodle/48/lisa-simpson.png
162,1,7,Bart Simpson,179,https://img.icons8.com/doodle/48/bart-simpson.png
174,1,7,Lisa Simpson,68,https://img.icons8.com/doodle/48/lisa-simpson.png
191,1,8,Bart Simpson,560,https://img.icons8.com/doodle/48/bart-simpson.png
207,1,8,Lisa Simpson,54,https://img.icons8.com/doodle/48/lisa-simpson.png
228,1,9,Bart Simpson,294,https://img.icons8.com/doodle/48/bart-simpson.png
234,1,9,Lisa Simpson,205,https://img.icons8.com/doodle/48/lisa-simpson.png
242,1,10,Bart Simpson,261,https://img.icons8.com/doodle/48/bart-simpson.png
259,1,10,Lisa Simpson,34,https://img.icons8.com/doodle/48/lisa-simpson.png
281,1,11,Bart Simpson,391,https://img.icons8.com/doodle/48/bart-simpson.png
293,1,11,Lisa Simpson,119,https://img.icons8.com/doodle/48/lisa-simpson.png
305,1,12,Bart Simpson,395,https://img.icons8.com/doodle/48/bart-simpson.png
320,1,12,Lisa Simpson,183,https://img.icons8.com/doodle/48/lisa-simpson.png
339,1,13,Bart Simpson,260,https://img.icons8.com/doodle/48/bart-simpson.png
347,1,13,Lisa Simpson,156,https://img.icons8.com/doodle/48/lisa-simpson.png

based on the code here : https://altair-viz.github.io/gallery/ranged_dot_plot.html

In [145]:
chart = (
    alt.Chart(data_q3)
    .transform_filter(
        alt.FieldOneOfPredicate(
            field="raw_character_text",
            oneOf=["Bart Simpson", "Lisa Simpson"]
        )
    )
    .encode(
        x=alt.X("word_count:Q", title="Word Count"),
        y=alt.Y("number_in_season:O", title="Episode Number in Season"),
        detail="number_in_season:O",
        tooltip=["season:O", "number_in_season:O", "raw_character_text:N", "word_count:Q"]
    )
)

line = chart.mark_line(color="#db646f", strokeWidth=4)

faces = chart.mark_image(width=20, height=20).encode(
    url="image:N"
)

(line + faces).properties(
    title="Bart vs Lisa Word Count by Episode (Season 1)",
    width=600,
    height=400
)

alt.LayerChart(...)

In [146]:
alt.Chart(data_q3).mark_bar().encode(
    x=alt.X('sum(word_count)').stack("normalize"),
    y='number_in_season:O',
    color='raw_character_text'
)

alt.Chart(...)

In [ ]:
data_q3

In [147]:
base = alt.Chart(data_q3).transform_density(
        'word_count',
        as_=['word_count', 'density'],
        groupby=['raw_character_text']
    )    

area = base.mark_area(opacity=0.5,tooltip=False).encode(
        x=alt.X('word_count:Q', 
                title='Word Count',
                axis=alt.Axis(format=',.0f')),
        y=alt.Y('density:Q', 
            stack=None,
            axis=None),
        color=alt.Color(
            'raw_character_text:N',
            title='Character',
            scale=alt.Scale(domain=['Lisa Simpson', 'Bart Simpson'], range=['#A96547', '#808080']),
            legend=alt.Legend(orient='top-right', strokeColor='black', fillColor='white', cornerRadius=5, padding=10)
        )
    )


line = base.mark_line(tooltip=False, stroke='black', strokeWidth=1.5).encode(
        x=alt.X('word_count:Q'),
        y=alt.Y('density:Q', axis=None),
        detail='raw_character_text:N'   #
    )

chart = (area + line).properties(
        title='Density of Episode-to-Episode Word Count Changes for Bart and Lisa (Season 1)',
        height=450
    ) 
chart

alt.LayerChart(...)

In [ ]:
irrelevant_words = ['you','0', 'a', 'over', 'i', 'the', 'to', 'and', 'is', 'of', 'it', 'in', 'im', 'so', 'if', 'too', 'our', 'be', '-', '--','1838', '4']

In [148]:
word_freq = (
    data.assign(word=data["normalized_text"].str.split())
        .explode("word")
        .groupby(["raw_character_text", "season","word"])
        .size()
        .reset_index(name="frequency")
)

In [149]:
import random
def shuffled_range(n): 
    return random.sample(range(n), k=n)

bart_season1 = word_freq[(word_freq['raw_character_text'] == 'Bart Simpson') & (word_freq['season'] == 1)]
bart_season1 = bart_season1[~bart_season1['word'].isin(irrelevant_words)]
bart_season1 = bart_season1[bart_season1['frequency'] > 5]
bart_season1['percentage'] = bart_season1['frequency'] / bart_season1['frequency'].sum() * 100
n = len(bart_season1)  
x = shuffled_range(n)
y = shuffled_range(n)

bart_season1 = bart_season1.assign(x=x, y=y)

lisa_season1 = word_freq[(word_freq['raw_character_text'] == 'Lisa Simpson') & (word_freq['season'] == 1)]
lisa_season1 = lisa_season1[~lisa_season1['word'].isin(irrelevant_words)]
lisa_season1 = lisa_season1[lisa_season1['frequency'] > 5]
lisa_season1['percentage'] = lisa_season1['frequency'] / lisa_season1['frequency'].sum() * 100
n = len(lisa_season1) 
x = shuffled_range(n)
y = shuffled_range(n)
lisa_season1 = lisa_season1.assign(x=x, y=y)

https://stackoverflow.com/questions/49566756/creating-wordclouds-with-altair

In [150]:
base_bart = alt.Chart(bart_season1).encode(
    x=alt.X('x:Q', axis=None),
    y=alt.Y('y:Q', axis=None)
)

word_cloud_bart = base_bart.mark_text(baseline='middle').encode(
    text='word:N',
    color=alt.Color('percentage:Q', scale=alt.Scale(scheme='oranges')),
    size=alt.Size('percentage:Q', legend=None)
).properties(
    title='Bart Simpson Word Cloud (Season 1)'
)

base_lisa = alt.Chart(lisa_season1).encode(
    x=alt.X('x:Q', axis=None),
    y=alt.Y('y:Q', axis=None)
)

word_cloud_lisa = base_lisa.mark_text(baseline='middle').encode(
    text='word:N',
    color=alt.Color('percentage:Q', scale=alt.Scale(scheme='blues')),
    size=alt.Size('percentage:Q', legend=None)
).properties(
    title='Lisa Simpson Word Cloud (Season 1)'
)

# facet of the two word clouds
(word_cloud_bart  | word_cloud_lisa).configure_view(strokeWidth=0).configure_title(
    fontSize=16,
    anchor='start'
)

alt.HConcatChart(...)

In [151]:
combined = word_freq[word_freq['season'] == 1]
combined = combined[combined['raw_character_text'].isin(['Bart Simpson', 'Lisa Simpson'])]
combined = combined[~combined['word'].isin(irrelevant_words)]
combined = combined.pivot(index = ['season','word'],columns='raw_character_text', values='frequency').reset_index().fillna(0)
combined = combined[(combined['Bart Simpson'] > 5) & (combined['Lisa Simpson'] > 5)]
combined = combined.melt(id_vars=['season','word'], value_vars=['Bart Simpson', 'Lisa Simpson'], var_name='character', value_name='frequency')
combined

    season   word     character  frequency
0        1  about  Bart Simpson       15.0
1        1    all  Bart Simpson       34.0
2        1    are  Bart Simpson       25.0
3        1     at  Bart Simpson       14.0
4        1   bart  Bart Simpson        9.0
..     ...    ...           ...        ...
93       1   what  Lisa Simpson       15.0
94       1   with  Lisa Simpson        7.0
95       1   yeah  Lisa Simpson       14.0
96       1   your  Lisa Simpson       11.0
97       1  youre  Lisa Simpson        8.0

[98 rows x 4 columns]

In [152]:
parallel_coordinates = alt.Chart(combined).mark_line(color='steelblue').encode(
    x = alt.X('character:N', title='Character'),
    y = alt.Y('frequency:Q', title='Word Frequency', axis = None),
    detail = alt.Detail('word:N')
).properties(
    title='Word Frequency Comparison between Bart and Lisa (Season 1)',
    width=400
).configure_title(
    fontSize=16,
    anchor='start'
)
parallel_coordinates

alt.Chart(...)

# Q4 would like the same comparison as before, but over a concrete episode

In [153]:
word_freq = (
    data.assign(word=data["normalized_text"].str.split())
        .explode("word")
        .groupby(["raw_character_text", "season", 'number_in_season',"word"])
        .size()
        .reset_index(name="frequency")
)

In [154]:
bart_season1 = word_freq[(word_freq['raw_character_text'] == 'Bart Simpson') & (word_freq['season'] == 1) & (word_freq['number_in_season'] == 6)]
bart_season1 = bart_season1[~bart_season1['word'].isin(irrelevant_words)]
#bart_season1 = bart_season1[bart_season1['frequency'] > 5]
bart_season1['percentage'] = bart_season1['frequency'] / bart_season1['frequency'].sum() * 100
n = len(bart_season1)  
x = shuffled_range(n)
y = shuffled_range(n)

bart_season1 = bart_season1.assign(x=x, y=y)

lisa_season1 = word_freq[(word_freq['raw_character_text'] == 'Lisa Simpson') & (word_freq['season'] == 1) & (word_freq['number_in_season'] == 6)]
lisa_season1 = lisa_season1[~lisa_season1['word'].isin(irrelevant_words)]
#lisa_season1 = lisa_season1[lisa_season1['frequency'] > 5]
lisa_season1['percentage'] = lisa_season1['frequency'] / lisa_season1['frequency'].sum() * 100
n = len(lisa_season1) 
x = shuffled_range(n)
y = shuffled_range(n)
lisa_season1 = lisa_season1.assign(x=x, y=y)

In [155]:
base_bart = alt.Chart(bart_season1).encode(
    x=alt.X('x:Q', axis=None),
    y=alt.Y('y:Q', axis=None)
)

word_cloud_bart = base_bart.mark_text(baseline='middle').encode(
    text='word:N',
    color=alt.Color('percentage:Q', scale=alt.Scale(scheme='oranges')),
    size=alt.Size('percentage:Q', legend=None)
).properties(
    title='Bart Simpson Word Cloud (Season 1 Episode 6) '
)

base_lisa = alt.Chart(lisa_season1).encode(
    x=alt.X('x:Q', axis=None),
    y=alt.Y('y:Q', axis=None)
)

word_cloud_lisa = base_lisa.mark_text(baseline='middle').encode(
    text='word:N',
    color=alt.Color('percentage:Q', scale=alt.Scale(scheme='blues')),
    size=alt.Size('percentage:Q', legend=None)
).properties(
    title='Lisa Simpson Word Cloud (Season 1 Episode 6) '
)

# facet of the two word clouds
(word_cloud_bart  | word_cloud_lisa).configure_view(strokeWidth=0).configure_title(
    fontSize=16,
    anchor='start'
)

alt.HConcatChart(...)

In [156]:
word_freq_lisa_bart = word_freq[(word_freq['season'] == 1) & (word_freq['number_in_season'] == 6) & (word_freq['raw_character_text'].isin(['Bart Simpson', 'Lisa Simpson']))]
word_freq_lisa_bart = word_freq_lisa_bart.groupby(['raw_character_text'])['frequency'].sum().reset_index()
word_freq_lisa_bart['image'] = word_freq_lisa_bart['raw_character_text'].map(images)
word_freq_lisa_bart

,raw_character_text,frequency,image
0,Bart Simpson,400,https://img.icons8.com/doodle/48/bart-simpson.png
1,Lisa Simpson,340,https://img.icons8.com/doodle/48/lisa-simpson.png

In [157]:
x_enc = alt.X(
    "raw_character_text:N",
    sort=word_freq_lisa_bart["raw_character_text"].tolist(),
    axis=alt.Axis(domain=False, ticks=False, labels=False,title = None)  # amaga labels de text
)

bars = alt.Chart(word_freq_lisa_bart).mark_bar().encode(
    x=x_enc,
    y=alt.Y("frequency:Q", title="Total Word Count"),
)

flags = (
    alt.Chart(word_freq_lisa_bart)
    .transform_calculate(zero="0")
    .mark_image(width=40, height=40, yOffset=14, clip=False)
    .encode(
        x= x_enc,
        y=alt.Y("zero:Q"),
        url="image:N"
    )
)

(bars + flags).resolve_scale(x="shared").properties(
    title="Total Word Count for Lisa and Bart in Season 1 Episode 6",
    height=360,
    width=400
)

alt.LayerChart(...)

evolució de les paraules en un espisodi cocnret??

In [158]:
data_q4_ts = data[(data['season'] == 4) & (data['number_in_season'] == 10)].copy()
characters = ['Bart Simpson', 'Lisa Simpson']
data_q4_ts = data_q4_ts[data_q4_ts['raw_character_text'].isin(characters)]
data_q4_ts['image'] = data_q4_ts['raw_character_text'].map(images)

In [159]:
alt.Chart(data_q4_ts).mark_tick().encode(
    x=alt.X('line_number_in_episode:Q', title='Line Number in Episode'),
    y=alt.Y('raw_character_text:N', title='Character'),
    tooltip=['line_number_in_episode', 'raw_character_text', 'word_count']
).properties(
    title='Dialogue Timeline for Bart and Lisa (Season 1 Episode 6)',
    height = 300
).configure_title(
    fontSize=16,
    anchor='start'
)

alt.Chart(...)

In [162]:
alt.Chart(data_q4_ts).mark_point(filled=True).encode(
    x=alt.X('line_number_in_episode:Q', title='Normalized Timestamp'),
    y=alt.Y('raw_character_text:N', title='Character'),
    tooltip=['timestamp_in_ms', 'raw_character_text', 'word_count'],
    color=alt.Size('word_count:Q', title='Word Count')
).properties(
    title='Dialogue Timeline for Bart and Lisa (Season 4 Episode 10)',
    height = 300,
    width = 600
).configure_title(
    fontSize=16,
    anchor='start'
)

alt.Chart(...)

In [163]:
y_enc = alt.Y(
    "raw_character_text:N",
    sort=data_q4_ts["raw_character_text"].tolist(),
    axis=alt.Axis(domain=False, ticks=False, labels=False,title = None))  # amaga labels de text


points = alt.Chart(data_q4_ts).mark_point(filled = True).encode(
    y=y_enc,
    x=alt.X('line_number_in_episode:Q', title='Line Number in Episode'),
    size=alt.Size('word_count:Q', title='Word Count')
)

flags = (
    alt.Chart(word_freq_lisa_bart)
    .transform_calculate(zero="0")
    .mark_image(width=40, height=40, xOffset=-20, clip=False)
    .encode(
        y= y_enc,
        x=alt.X("zero:Q"),
        url="image:N"
    )
)

(points + flags).resolve_scale(x="shared").properties(
    title="Total Word Count for Lisa and Bart in Season 1 Episode 6",
    height=360,
    width=400
)

alt.LayerChart(...)

In [164]:
data_q4_ts2 = data[(data['season'] == 8) & (data['number_in_season'] == 9)].copy()
characters = ['Marge Simpson', 'Coyote']
data_q4_ts2 = data_q4_ts2[data_q4_ts2['raw_character_text'].isin(characters)]

In [165]:
word_freq_marge_homer = word_freq[(word_freq['season'] == 8) & (word_freq['number_in_season'] == 9) & (word_freq['raw_character_text'].isin(['Marge Simpson', 'Coyote']))]
word_freq_marge_homer = word_freq_marge_homer.groupby(['raw_character_text'])['frequency'].sum().reset_index()
word_freq_marge_homer['image'] = word_freq_marge_homer['raw_character_text'].map(images)
word_freq_marge_homer

,raw_character_text,frequency,image
0,Coyote,128,https://static.simpsonswiki.com/images/7/73/Ta...
1,Marge Simpson,326,https://img.icons8.com/doodle/48/marge-simpson...

In [166]:
y_enc = alt.Y(
    "raw_character_text:N",
    sort=data_q4_ts2["raw_character_text"].tolist(),
    axis=alt.Axis(domain=False, ticks=False, labels=False,title = None))  # amaga labels de text


points = alt.Chart(data_q4_ts2).mark_point(filled = True).encode(
    y=y_enc,
    x=alt.X('line_number_in_episode:Q', title='Line Number in Episode'),
    size=alt.Size('word_count:Q', title='Word Count')
)

flags = (
    alt.Chart(word_freq_marge_homer)
    .transform_calculate(zero="0")
    .mark_image(width=40, height=40, xOffset=-20, clip=False)
    .encode(
        y= y_enc,
        x=alt.X("zero:Q"),
        url="image:N"
    )
)

(points + flags).resolve_scale(x="shared").properties(
    title="Total Word Count for Lisa and Bart in Season 1 Episode 6",
    height=360,
    width=400
)

alt.LayerChart(...)

# Q5 Sentences

hi ha frases repetides

In [167]:
data_q5 = data.groupby(['raw_character_text']).size().reset_index(name='number_of_sentences')
data_q5

               raw_character_text  number_of_sentences
0            "For Dummies" Author                    1
1     "Just Stamp the Ticket" Man                    5
2                      "Mario" #2                    1
3                   "Shorts" Bart                    3
4                  "Shorts" Homer                    5
...                           ...                  ...
6269                         iPod                    1
6270           newsstand Operator                    1
6271                            t                    1
6272                      teacher                    5
6273                         Üter                   15

[6274 rows x 2 columns]

In [168]:
data_q5.sort_values(by='number_of_sentences', ascending=False, inplace=True)
alt.Chart(data_q5.head(20)).mark_bar().encode(
    x=alt.X('raw_character_text', sort='-y', title='Character'),
    y=alt.Y('number_of_sentences', title='Number of Sentences'),
    tooltip=['raw_character_text', 'number_of_sentences']
).properties(
    title='Number of Sentences per Character'
).configure_axisX(
    labelAngle=-45,
    labelFontSize=12
).configure_title(
    fontSize=16,
    anchor='start'
)

alt.Chart(...)

In [173]:
characters = images.keys()
data_q5_main = data_q5[data_q5['raw_character_text'].isin(characters)]
data_q5_main['image'] = data_q5_main['raw_character_text'].map(images)

/var/folders/95/s4thp5290fd41pw2cj8713k80000gn/T/ipykernel_59502/3472017053.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_q5_main['image'] = data_q5_main['raw_character_text'].map(images)

In [174]:
data_q5_main = data_q5_main.merge(data_q1_image[['raw_character_text', 'word_count']], on='raw_character_text', how='left')
data_q5_main

,raw_character_text,number_of_sentences,image,word_count
0,Homer Simpson,27908,https://img.icons8.com/doodle/48/homer-simpson...,273419
1,Marge Simpson,13190,https://img.icons8.com/doodle/48/marge-simpson...,125349
2,Bart Simpson,13011,https://img.icons8.com/doodle/48/bart-simpson.png,109983
3,Lisa Simpson,10767,https://img.icons8.com/doodle/48/lisa-simpson.png,99857
4,C. Montgomery Burns,3086,https://img.icons8.com/doodle/48/charles-montg...,36577
5,Moe Szyslak,2810,https://img.icons8.com/doodle/48/bartender-mo.png,33171
6,Ned Flanders,2056,https://img.icons8.com/doodle/48/ned-flanders.png,23380
7,Grampa Simpson,1807,https://img.icons8.com/doodle/48/abraham-simps...,19650
8,Chief Wiggum,1796,https://img.icons8.com/doodle/48/clancy-wiggum...,20130
9,Milhouse Van Houten,1750,https://img.icons8.com/doodle/48/milhouse-van-...,14627
10,Krusty the Clown,1704,https://img.icons8.com/doodle/48/krusty-the-cl...,20945
11,Nelson Muntz,1145,https://static.simpsonswiki.com/images/0/0c/Ta...,8551
12,Lenny Leonard,1144,https://static.simpsonswiki.com/images/6/6f/Ta...,9917
13,Apu Nahasapeemapetilon,988,https://static.simpsonswiki.com/images/0/08/Ta...,11657
14,Waylon Smithers,965,https://static.simpsonswiki.com/images/3/3a/Ta...,9604
15,Kent Brockman,884,https://static.simpsonswiki.com/images/3/35/Ta...,16177
16,Carl Carlson,852,https://static.simpsonswiki.com/images/a/a4/Ta...,7221
17,Edna Krabappel-Flanders,725,https://static.simpsonswiki.com/images/1/14/Ta...,7354
18,Dr. Julius Hibbert,673,https://static.simpsonswiki.com/images/d/d5/Ta...,7821
19,Selma Bouvier,566,https://static.simpsonswiki.com/images/8/8f/Ta...,4973
20,Barney Gumble,559,https://img.icons8.com/doodle/48/barney-gumble...,4508
21,Rev. Timothy Lovejoy,554,https://static.simpsonswiki.com/images/4/40/Ta...,6905
22,Sideshow Bob,527,https://static.simpsonswiki.com/images/6/68/Ta...,6444
23,Gary Chalmers,519,https://static.simpsonswiki.com/images/5/58/Ta...,5759
24,Groundskeeper Willie,496,https://static.simpsonswiki.com/images/4/40/Ta...,4837
25,Mayor Joe Quimby,495,https://static.simpsonswiki.com/images/e/e3/Ta...,6173
26,Ralph Wiggum,469,https://img.icons8.com/doodle/48/ralf.png,3061
27,Comic Book Guy,463,https://static.simpsonswiki.com/images/a/a9/Ta...,5813
28,Patty Bouvier,462,https://static.simpsonswiki.com/images/3/31/Ta...,3816
29,Otto Mann,407,https://static.simpsonswiki.com/images/4/48/Ta...,3615
30,Martin Prince,388,https://static.simpsonswiki.com/images/d/da/Ta...,3770
31,Jimbo Jones,347,https://static.simpsonswiki.com/images/f/f3/Ta...,2674
32,Lou,343,https://static.simpsonswiki.com/images/c/cf/Ta...,2712
33,Sideshow Mel,342,https://static.simpsonswiki.com/images/6/6d/Ta...,3366
34,Professor Jonathan Frink,329,https://static.simpsonswiki.com/images/0/09/Ta...,4876
35,Fat Tony,276,https://static.simpsonswiki.com/images/1/1b/Ta...,2980
36,Agnes Skinner,258,https://static.simpsonswiki.com/images/b/b1/Ta...,2478
37,Kirk Van Houten,237,https://static.simpsonswiki.com/images/6/61/Ta...,2514
38,Cletus Spuckler,225,https://static.simpsonswiki.com/images/a/a0/Ta...,2362
39,Duffman,89,https://static.simpsonswiki.com/images/1/18/Ta...,970
40,Frank Grimes,59,https://static.simpsonswiki.com/images/a/a0/Ta...,792
41,Coyote,11,https://static.simpsonswiki.com/images/7/73/Ta...,128

no ens fixen en uniqye, ens fixem purament en el total de words

In [175]:
alt.Chart(data_q5_main).mark_image(width=30, height=30).encode(
    x = alt.X('word_count', title='Total Word Count'),
    y = alt.Y('number_of_sentences', title='Number of Sentences'),
    url = 'image',
    tooltip = ['raw_character_text', 'word_count', 'number_of_sentences']
).properties(
    title='Total Word Count vs Number of Sentences for Main Characters'
).configure_title(
    fontSize=16,
    anchor='start'
)

alt.Chart(...)